# Generated by Django 2.2.4 on 2019-08-09 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sounds', '0002_auto_20190809_1806'),
    ]

    operations = [
        migrations.AddField(
            model_name='soundbyte',
            name='file',
            field=models.FileField(null=True, upload_to='sounds'),
        ),
    ]
