# Generated by Django 2.2.4 on 2019-08-09 19:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sounds', '0003_soundbyte_file'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='soundbyte',
            name='path',
        ),
    ]
