# Generated by Django 2.2.4 on 2019-08-09 19:42

from django.db import migrations, models
import sounds.models


class Migration(migrations.Migration):

    dependencies = [
        ('sounds', '0004_remove_soundbyte_path'),
    ]

    operations = [
        migrations.AlterField(
            model_name='soundbyte',
            name='file',
            field=models.FileField(null=True, upload_to=sounds.models.upload_file_path),
        ),
    ]
