# Generated by Django 2.2.4 on 2019-08-12 16:15

from django.db import migrations, models
import sounds.models


class Migration(migrations.Migration):

    dependencies = [
        ('sounds', '0005_auto_20190809_1942'),
    ]

    operations = [
        migrations.AlterField(
            model_name='soundbyte',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to=sounds.models.upload_file_path),
        ),
    ]
