# Generated by Django 2.2.4 on 2019-08-12 16:26

from django.db import migrations, models
import sounds.models


class Migration(migrations.Migration):

    dependencies = [
        ('sounds', '0006_auto_20190812_1615'),
    ]

    operations = [
        migrations.AlterField(
            model_name='soundbyte',
            name='file',
            field=models.FileField(null=True, upload_to=sounds.models.upload_file_path),
        ),
    ]
